version: '3.6'

services:

  flask_ubuntu:
    build:
      context: ./services/flask_ubuntu
      dockerfile: Dockerfile-dev
    volumes:
      - './services/flask_ubuntu:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig

  flask_alpine:
    build:
      context: ./services/flask_alpine
      dockerfile: Dockerfile-dev
    volumes:
      - './services/flask_alpine:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask_ubuntu
      - flask_alpine
