# base image
FROM python:3.6.5-alpine

# new
# install dependencies
RUN apk update && apk add --virtual build-deps gcc python-dev musl-dev

# set working directory
WORKDIR /usr/src/app

# ad and install requirements
COPY requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod 755 /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["sh", "/usr/src/app/entrypoint.sh"]
